name: Spec Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Insomnia CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 3.12.0

      - name: Run a multi-line script
        run: |
          inso generate config spec.yaml -t kubernetes > teste.yaml
          cat teste.yaml
          mv teste.yaml ./artefatos
          
